version: "3"
services:
    webapp:
        image: centos/httpd
        container_name: webapp
        ports:
        - "8001:80"
        volumes:
        - webapp:/var/www/html:rw
        depends_on:
        - webapp-db
    webapp-db:
        image: mariadb
        container_name: webapp-db
        environment:
          MYSQL_ROOT_PASSWORD: arla1983
          MYSQL_DATABASE: docker
        volumes:
        - webapp-db:/var/lib/mysql:rw
volumes:
    webapp: {}
    webapp-db: {}





