version: "3"
services:
    webapp:
        image: devopstrainer/deploy:webapp
        container_name: webapp
        ports:
        - "8001:80"
        depends_on:
        - webapp-db
    webapp-db:
        image: mariadb
        container_name: webapp-db
        environment:
          MYSQL_ROOT_PASSWORD: arla1983
          MYSQL_DATABASE: docker
