version: "3"
services:
  web:
    image: ubuntu/apache2
    container_name: web
    ports:
    - "8005:80"
    volumes:
    - web:/var/www/html:rw
    depends_on:
    - db
  db:
    image: mariadb
    container_name: db
    volumes:
    - db:/var/lib/mysql:rw
volumes:
  web: {}
  db: {}  

